server:
  port: 80
  address: 127.0.0.1
spring:
  profiles:
    # 外置jdbc、redis和mail配置文件
    active: jdbc,redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

  thymeleaf:
    prefix: classpath:/templates/

# MyBatis配置
mybatis:
  configuration:
    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
  #配置MyBatis的xml映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.kkindom_blog.model.domain

#浏览器cookie相关设置
COOKIE:
  # 设置cookie默认时长为30分钟
  VALIDITY: 1800
  mvc:
    hiddenmethod:
      filter:
        enabled: true